# Generated by Django 5.1.4 on 2025-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0044_kardex_fuente_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='numero_kardex',
            field=models.CharField(
                max_length=20,
                null=True,     # ✅ permite valores nulos en la base de datos
                blank=True,    # ✅ permite que los formularios lo dejen vacío
                editable=False,
                unique=True
            ),
        ),
    ]
