# Generated by Django 5.1.4 on 2026-07-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0051_articulo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardex',
            name='numero_kardex',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
