# Generated by Django 5.1.4 on 2026-07-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen_app', '0052_alter_kardex_numero_kardex'),
        ('almacen_app', '0052_solicitudrequerimiento_tipos_solicitud'),
    ]

    operations = [
    ]
